version: '2'
services:
  springbootapp:
    image: porichigo15/springbootapp:0.0.1
    container_name: springbootapp
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://productdb:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false
    ports:
      - 8080:8080

  mariadb:
    image: mysql:latest
    container_name: mysql-db-1
    volumes:
      - /home/docker/volumes/myapp/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=user-service
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8